### ISSUE TITLE
[Bug]: Fix Cannon Bin Coding

### ISSUE THREAD

**Issue by Slickbird** [monadicus/snarkops#130]
- fix cannon bincoding (this fails rn for some reason)
```yaml
---
version: cannon.snarkos.testing.monadic.us/v1

name: passive-cannon
instance: true

source:
  tx-modes: [transfer-public]
  private-keys: [committee.$]
  addresses: [committee.$]

sink:
  target: client/*
  tx-delay-ms: 1000
````
