### ISSUE TITLE
✅ Execute Timeline Action

### ISSUE THREAD

**Issue by gluax** [monadicus/snarkops#132]
A timeline action that can fire transactions (by id, from a cache or something) or generate authorizations using the compute pool.

```yaml
  - execute:
    - transaction: atalsdjfakjsldhfkjasdhfTRANSACTIONHASH
      cannon: <cannon-id>
    - program: credits.aleo
      function: transfer_public
      target: <listen mode cannon-id? node-id?>
      args: 
        - private_key: committee.0
        - value: 0u64
        - address: committee.1
  ```

This would enable the following:
- Custom program and function calls.
- Bonding/unbonding actions
- etc

Blocked by #133
