### ISSUE TITLE
✅ Specify aot binary (or path) from YAML 

### ISSUE THREAD

**Issue by Meshiest** [monadicus/snarkops#235]
## ✅ Task

In the prepare doc for storage an additional component should be added:

```yaml
bins:
  <bin_name>: <bin_path | bin_url | { url: bin_url, sha256sum: <sha256> }>
  remote_bin_simple: https://path/to/bin/download
  remote_bin_secure:
    url: https://path/to/bin/download
    sha256sum: <sha sum>
  local_bin: ./path/on/control_plane/host
```

This data should be forwarded to the agent in StorageInfo/EnvInfo and used to determine the source of the binary to use
